export type TypeLawyer = {
    activities: any,
    awards: any,
    bookmarks: any,
    career: any,
    city: any,
    detailContents: any,
    detailTitle: any,
    education: any,
    fee: any,
    fields: any,
    fileNameList: any,
    isApproved: any,
    location: any,
    name: any,
    news: any,
    officeInfo: any,
    papers: any,
    qualifications: any,
    services: any,
    shortDesc: any,
    tags: any,
    updatedAt: any,
    userId: any,
    userPwd: any,
    _id: any,
}

export type TypeBookMark = {
    clientUserId: any,
    createDate: any,
    createdAt: any,
    lawyerImage: any,
    lawyerName: any,
    lawyerUserId: any,
    _id: any,
}
